-- Table NGUOIDUNG
CREATE TABLE NGUOIDUNG (
    USERNAME VARCHAR(50) PRIMARY KEY,
    MATKHAU VARCHAR(100),
    EMAIL VARCHAR(100),
    HOTEN NVARCHAR(100),
    ROLE VARCHAR(50),
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0
);

-- Table MON
CREATE TABLE MON (
    MAMON INT PRIMARY KEY,
    TENMON VARCHAR(100),
    MOTA NVARCHAR(200),
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0
);

-- Table NGUOIDUNG_MON
CREATE TABLE NGUOIDUNG_MON (
    MAND VARCHAR(50),
    MAMON INT,
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0,
    PRIMARY KEY (MAND, MAMON),
    FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(USERNAME),
    FOREIGN KEY (MAMON) REFERENCES MON(MAMON)
);

-- Table DETHI
CREATE TABLE DETHI (
    MADT INT PRIMARY KEY,
    TIEUDE NVARCHAR(100),
    MAMON INT,
    MUCDO VARCHAR(50),
    NGAYTAO DATETIME,
    NGUOITAO VARCHAR(50),
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0,
    FOREIGN KEY (MAMON) REFERENCES MON(MAMON),
    FOREIGN KEY (NGUOITAO) REFERENCES NGUOIDUNG(USERNAME)
);

-- Table KETQUA
CREATE TABLE KETQUA (
    MAKQ INT PRIMARY KEY,
    DIEM FLOAT,
    NGAYHOANTHANH DATETIME,
    USERNAME VARCHAR(50),
    MADT INT,
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0,
    FOREIGN KEY (USERNAME) REFERENCES NGUOIDUNG(USERNAME),
    FOREIGN KEY (MADT) REFERENCES DETHI(MADT)
);


-- Table CAUHOI
CREATE TABLE CAUHOI (
    MACAUHOI INT PRIMARY KEY,
    TIEUDE NVARCHAR(255),
    KIEUCAUHOI VARCHAR(50),
    MADT INT,
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0,
    FOREIGN KEY (MADT) REFERENCES DETHI(MADT)
);

-- Table LUACHON
CREATE TABLE LUACHON (
    MALC INT PRIMARY KEY,
    MACAUHOI INT,
    TENLUACHON VARCHAR(100),
    NOIDUNG NVARCHAR(100),
    ISCORRECT BIT,
    createdAt DATETIME,
    updatedAt DATETIME,
    isDeleted BIT DEFAULT 0,
    FOREIGN KEY (MACAUHOI) REFERENCES CAUHOI(MACAUHOI)
);
